### ISSUE TITLE
Broken preview links

### ISSUE THREAD

**Issue by nurse-curtis** [joshp23/YOURLS-Snapshot#13]
I'm using the current MASTER of this plugin, and have installed according to your instructions.  The appropriate folders were created, and it is definitely generating previews! Unfortunately, all previews are shown as broken links, the error when trying to load is "FAIL: missing passkey" (I tested, and Snapshot is not sending any of the 3 parameters to usrv.
- the link to srv seems to work fine, as I get the 'die' errors.
- the cache is populated, shows the correct total of files in the Snapshot admin interface

I, unfortunately, do not know how to test why Snapshot is doing all of the processing correctly, but not sending the appropriate variables to /srv/

Any suggestions?

**Comment by jhollowe** [comment]
I'm having a similar issue, and I think I know what the issue is. I'll try to get a PR in within the next few days.

**Comment by zmbcgn** [comment]
And? I still have this issue :/

**Comment by jhollowe** [comment]
I wasn't able to get it figured out and haven't looked at it much since.

**Comment by joshp23** [comment]
Just verified that, properly configured, this works with v3.0.4 with YOURLS 1.7.10 under NGINX with PHP-7.3. The missing passkey error has me confused. Is this what everybody is getting, specifically?

**Comment by joshp23** [comment]
A similar issue https://github.com/joshp23/YOURLS-U-SRV/issues/7#issuecomment-797698405 with a fix coming soon

**Comment by joshp23** [comment]
Try updating to USRV [2.3.4](https://github.com/joshp23/YOURLS-U-SRV/releases/tag/2.3.4)

**Comment by zmbcgn** [comment]
tried with updating. same behaviour as before

**Comment by joshp23** [comment]
@zmbcgn , and you are getting the error, "Missing Passkey" here?

**Comment by joshp23** [comment]
@zmbcgn ? If you could clearly describe the behavior, or verify if you are or aren't getting the "Missing Passkey" error, that would help me focus in on a potential bug.

**Comment by zmbcgn** [comment]
Yes. I'm getting the missing passkey error, when I right-click on the broken image and open the picture in a new tab. Sorry for the delay.

**Comment by zmbcgn** [comment]
I created a Link on my YOURLS installation at https://5711.org. This Link is for example https://5711.org/speed . The preview will be then https://5711.org/speed~ . Though I don't actually see a preview. I see a broken image and when I right-click on it, it'll say "missing passkey".

USRV version 2.3.4
snapshot version 3.0.4
yourls version 1.8.2 with sleeky

**Comment by zmbcgn** [comment]
I ust found the error.txt file in the plugins directory. 

maybe this helps?

```
# NEW ERROR RECORD START: 2021-09-22 22:51:35
# KEYWORD: speed
# URL: https://www.speedtest.net/
#
Screen\Exceptions\PhantomJsException: Auto configuration failed
140710091077568:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libssl_conf.so): libssl_conf.so: cannot open shared object file: No such file or directory
140710091077568:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140710091077568:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error loading dso:conf_mod.c:285:module=ssl_conf, path=ssl_conf
140710091077568:error:0E076071:configuration file routines:MODULE_RUN:unknown module name:conf_mod.c:222:module=ssl_conf in /var/www/5711.org/pages/user/plugins/snapshot/assets/screen/src/Capture.php:247
Stack trace:
#0 /var/www/5711.org/pages/user/plugins/snapshot/plugin.php(743): Screen\Capture->save()
#1 /var/www/5711.org/pages/user/plugins/snapshot/plugin.php(709): snapshot_screen()
#2 /var/www/5711.org/pages/user/plugins/snapshot/plugin.php(608): snapshot_request()
#3 /var/www/5711.org/pages/user/plugins/snapshot/plugin.php(566): snapshot_show()
#4 /var/www/5711.org/pages/includes/functions-plugins.php(232): snapshot_precheck()
#5 /var/www/5711.org/pages/includes/functions-plugins.php(282): yourls_apply_filter()
#6 /var/www/5711.org/pages/yourls-loader.php(25): yourls_do_action()
#7 {main}
#
```

libssl1.1, libssl1.0.4 and libssl-dev is installed.

**Comment by zmbcgn** [comment]
Maybe related to this?
https://github.com/bazelbuild/rules_closure/issues/351
